### ISSUE TITLE
Ma tache (sidebar + menu)

### ISSUE THREAD

**Issue by Anassifi** [abdellmum/building__front-end__web__application#17]
En concernent ma tache est ce que je doit faire la sidebar et le menu j'ai pas bien compris si possible une explication je veux pas commancer sans comprendre et finir par refaire le travail #14

**Comment by abdellmum** [comment]
comme je t'ai dit sur discord @Anassifi . regarde bien le wireframing hight-fidelity 
et applique ce qu'on discuté hier .bon courage

**Comment by Anassifi** [comment]
@abdellmum Mais il n'y a pas de conception de barre latérale

**Comment by tijaniabdellatif** [comment]
Pour le container :  `<body class="container"><div class="sidebar"></div></body>`

 ```
.container{
    display:grid;
    grid-template-rows: 80vh min-content 40vw repeat(3,min-content);
    grid-template-columns: [sidebar-start]8rem [sidebar-end full-start] minmax(6rem,1fr) [center-start] repeat(8,[col-start] minmax(min-content,15rem)[col-end]) [center-end] minmax(6rem,1fr) [full-end]; //1fr min-content(intrinseque et  extrinseque) 
    
}
```
maintenant la sidebar : 
 
```
.sidebar{
    background-color: rgba($color-primary,.7);
    grid-column: sidebar-start / sidebar-end;
    grid-row: 1/-1;
}
```

**Comment by abdellmum** [comment]
@tijaniabdellatif  mais Mr nous avons suprimmé le body class container pcq il nous a causé bcp de problémes

**Comment by tijaniabdellatif** [comment]
J'ai donné juste un petit exemple que vous pouvez le personnalisé.

**Comment by Anassifi** [comment]
Puis-je utiliser javascript pour créer le nav parce que c'est beaucoup plus facile ? @tijaniabdellatif

**Comment by abdellmum** [comment]
Pure css @Anassifi 
C'est le PO nous a demandé

**Comment by Anassifi** [comment]
Okay ça marche
