### ISSUE TITLE
ajouter header vérifier  

### ISSUE THREAD

**Issue by othmane-qr** [abdellmum/building__front-end__web__application#18]

**Comment by Anassifi** [comment]
Bonne travail je viens de verifier est ce que c'est tout dans le header ? @othmane-qr

**Comment by abdellmum** [comment]
@Anassifi non on a juste pushé notre travail pour tester l'automatiosation que nous avons fait avec NPM

bref tu dois fetcher et puller aprés chaque issue pour vois les modifications et donner ton opinion 

courage HAKIM

**Comment by Anassifi** [comment]
Merci je vais faire le fetch et pull pour voir les modifs
