### ISSUE TITLE
Vérification du contact

### ISSUE THREAD

**Issue by Salma-hu** [abdellmum/building__front-end__web__application#21]
Vous avez phushé contact, veuillez vérifier

**Comment by othmane-qr** [comment]
bon travail ajouter hover  sur le botton

**Comment by othmane-qr** [comment]
bon travail ajouter l'hover sur le bouton

**Comment by Salma-hu** [comment]
Je vais y travailler @othmane-qr

**Comment by Anassifi** [comment]
Bonne travail je viens de verifier ça marche
