### ISSUE TITLE
liaison de sidbar aux autres sections

### ISSUE THREAD

**Issue by abdellmum** [abdellmum/building__front-end__web__application#26]
@Anassifi bonjour mr hakim
svp veillez lier la sidebar aux autres sections . et verifiez si ca marche bien

n'oubliez pas que la sidebar doit se casher en cliquant sur un de ses elements

**Comment by Anassifi** [comment]
Je vérifierai si c'est possible attender mon retour.

**Comment by abdellmum** [comment]
Good

**Comment by abdellmum** [comment]
on attends mr hakim . 
deja trop tard

**Comment by Anassifi** [comment]
J'ai tout essayé mais cette chose n'existe pas sans Javascript. Je pense que je viens de perdre mon temps sur celui-ci Mr Karim.

**Comment by tijaniabdellatif** [comment]
@Anassifi  , ça existe with CSS en utilisant la pseudo Classe `::target` , et tu va pas perdre du temps en explorant une autre technique sans utiliser JAVASCRIPT.

**Comment by tijaniabdellatif** [comment]
sur cette partie utilisez les pseudos classe `::target` `::active ::visited` `::hover`
