### ISSUE TITLE
vérifiez les sections 

### ISSUE THREAD

**Issue by othmane-qr** [abdellmum/building__front-end__web__application#7]

**Comment by abdellmum** [comment]
les icones sur la section features sont plus grandes othmane

**Comment by othmane-qr** [comment]
ok je modifie les tailles des icones

**Comment by othmane-qr** [comment]
vérifiez les modification  les tailles des icônes @abdellmum

**Comment by abdellmum** [comment]
@othmane-qr @chiamae dont forget to close your issue
